apiVersion: apps/v1
kind: Deployment
metadata:
  name: apuestas-service
  labels:
    app: apuestas-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apuestas-service
  template:
    metadata:
      labels:
        app: apuestas-service
    spec:
      containers:
      - name: apuestas-service
        image: 605493908341.dkr.ecr.us-east-1.amazonaws.com/apuestas-service:latest
        ports:
        - containerPort: 8005
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          tcpSocket:
            port: 8005
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /livez
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: apuestas-service
spec:
  type: ClusterIP
  selector:
    app: apuestas-service
  ports:
  - port: 8005
    targetPort: 8005